### ISSUE TITLE
Pass instance in click callback

### ISSUE THREAD

**Issue by visualbuffer** [ray-pH/diagramatics#13]
[feature request]
**Description**
The callback can include the instance which allows us to customize the behavior easily. Currently we can do it by passing two separate instance. If the click behavior needs to be stateful, as in each click has a different behavior we can implement it easily by passing down the instance

```javascript
// click button doesn't have a state, so it can't be accessed 
// using `int.get()` or `inp[name]` inside `int.draw_function`

let sq = square(40);
let button = square(10).fill('lightgrey');
let button_pressed = square(10).fill('blue');

draw(sq);

const callback = (e) => {
    e.fill('red')
}
int.('b', button, button_pressed, callback);
int.draw();
```

**Comment by ray-pH** [comment]
You can manage your own state by using some variables. 

you can do something like this.
```javascript
let button = square(10).fill('lightgrey').translate(V2(0,-10));
let button_pressed = button.fill('blue');

let state = 0;
let colors = ['white', 'red', 'yellow', 'green', 'blue'];
int.draw_function = (inp) => {
  let color = colors[state];
  let sq = square(40).fill(color);
  draw(sq); 
}

const callback = () => {
    state = (state + 1) % colors.length
}
int.button_click('b', button, button_pressed, callback);
int.draw();
```

*NOTE: you are supposed to think of the diagram object as an immutable object, so changing the color using `e.fill()` wouldn't suppose to work anyway. something like this code will not draw a "red" square, but a "blue" square instead
```javascript
let sq = square(10).fill('blue')
sq.fill('red')

draw(sq)
```
unless, of course, you tag it as mutable
```javascript
let sq = square(10).fill('blue').mut()
sq.fill('red')

draw(sq) // will draw a red square
```

-----------------------
I guess what you need and what's missing from the library is the ability to change the diagram object of a button. Because right now, if you define a button like this
```javascript
int.button_click('b', diagram1, diagram2, callback);
```
you're stuck with that `diagram1` and `diagram2`

I think we need to try to implement a simple way to change that, maybe something like this
```javascript
int.button_click_change_diagram('b', new_diagram1)
int.button_click_change_presed_diagram('b', new_diagram2)
int.button_click_change_callback('b', new_callback)

// or
int.button_click_change('b', new_diagram1, new_diagram2, new_callback)
```
Or, to make it simpler, we can reuse the method name `button_click()`, and if the button with the provided name already exists, instead of creating a new one, it will modify the existing one instead. So you can do something like

```javascript
let sq = square(40);
let button = square(10).fill('lightgrey');
let button_pressed = square(10).fill('blue');

draw(sq);

const callback = (e) => {
    let new_button = button.fill('red')
    int.button_click('b', new_button, button_pressed, callback);
}
int.button_click('b', button, button_pressed, callback);
int.draw();
```

I think i can work on that. Thanks for opening the issue, let me know what you think about my suggestion

**Comment by visualbuffer** [comment]
Thanks for laying out the reasoning and the workarounds. 
My use case dealt with multiple-click objects. For instance, in visualizing matrix operations, an easy way to code it would be to use the diagram instance and adjust the behaviour. If there are performance issues with mutable objects then we have to use workarounds.

I think we need the functionalities you had outlined above: button_click_change_diagram , button_click_change_callback .. and others such which we have not thought through. Passing the instance might have made it simpler though imho.

**Comment by ray-pH** [comment]
> Diagramatics@1.2.8

If you want to edit the diagram for a button, you can call the function again (`int.button_click()` or `int.button_toggle()` with the new diagram)

example
```javascript
let button = square(10).fill('white');
let button_pressed = button.fill('lightgrey');

let state = 0;
let colors = ['white', 'red', 'yellow', 'green', 'blue'];

let sq = square(40);
draw(sq); 

const callback = () => {
    state = (state + 1) % colors.length
    let color = colors[state];
    int.button_click('b', button.fill(color), button_pressed, callback);
    console.log(state)
}
int.button_click('b', button, button_pressed, callback);
int.draw();
```

Regarding state management, to make the library simpler, I feel like it's okay to make it the responsibility of the user to manage their own state, for example:

```javascript
let button = square(10).fill('white');
let colors = ['white', 'red', 'yellow', 'green', 'blue'];

let sq = square(40);
draw(sq); 

let button_a = button.translate(V2(-10,0));
let button_pressed_a = button_a.fill('lightgray');
let state_a  = 0;
let callback_a = () => {
    state_a = (state_a + 1) % colors.length;
    button_a = button_a.fill(colors[state_a]).rotate(to_radian(5));
    button_pressed_a = button_a.fill('lightgray');
    int.button_click('a', button_a, button_pressed_a, callback_a);
}
int.button_click('a', button_a, button_pressed_a, callback_a);

let button_b = button.translate(V2(10,0));
let button_pressed_b = button_b.fill('lightgray');
let state_b  = 0;
let callback_b = () => {
    state_b = (state_b + 1) % colors.length;
    button_b = button_b.fill(colors[state_b]).rotate(to_radian(-5));
    button_pressed_b = button_b.fill('lightgray');
    int.button_click('b', button_b, button_pressed_b, callback_b);
}
int.button_click('b', button_b, button_pressed_b, callback_b);

int.draw();
```

> For the example above, you can avoid repetition by utilizing functions, arrays, or other JavaScript functionalities; however, it's up to the user to implement these solutions.
