### ISSUE TITLE
First example doesn't work on firefox

### ISSUE THREAD

**Issue by FruitcakeElemental** [ray-pH/diagramatics#2]
On this page https://photon-ray.xyz/diagramatics-site/

The first example on the left (the weight with pully) doesn't work on firefox, I tested with Chrome and it works. The drag control doesn't seem to function correctly. The 2nd and 3rd examples appear to function correctly.

**Comment by ray-pH** [comment]
Oh, i just noticed that Firefox doesn't support `TouchEvent`.  Will work on it
