### ISSUE TITLE
Darkmode support

### ISSUE THREAD

**Issue by FruitcakeElemental** [ray-pH/diagramatics#3]
A common feature for the modern UI experience is dark mode however it doesn't appear your website supports it. Neither do the interactive diagrams. I use dark reader to make websites dark but it struggles on non static elements such as your diagrams.

I'd look into making sure dark mode is supported as a usability feature.

**Comment by ray-pH** [comment]
I'm not sure whether that feature is supposed to be supported directly in the library or whether it's the user that has to configure that one themself.

For now, I think it's the responsibility of the user to provide themes and multiple diagrams or diagram styles that can be swapped depending on the theme.
In this case, it'll still be nice to support a dark theme on the website, but I suppose that will be an issue for separate repo [https://github.com/ray-pH/diagramatics-site](https://github.com/ray-pH/diagramatics-site)
