### ISSUE TITLE
Bug in xyaxes display

### ISSUE THREAD

**Issue by yaoshenwang** [ray-pH/diagramatics#64]
When the value range of the parameter is greater than 5, a bug will occur where some numbers disappear.

Example code:
```
let opt = {
    xrange : [-6, 5],
    yrange : [-6, 5],
}
let ax = xyaxes(opt);
draw(ax);
```

Shown image:
![image](https://github.com/ray-pH/diagramatics/assets/23271198/575c1523-74a2-4963-9811-96265982bebf)

 (obviously some numbers disappear)

**Comment by yaoshenwang** [comment]
maybe something wrong with function xticks and yticks in shapes_graph.ts ?

**Comment by ray-pH** [comment]
I've added a tweak in #65 
Automatically calculating the tick interval has always been tricky for me

If you need to define your own tick positions, you can do that via `xticks` and `yticks` key

```javascript
let opt = {
    xrange : [-6, 5],
    yrange : [-6, 5],
    xticks : [-5,-4,1,2],
    yticks : range_inc(-5,4).filter(x => x)
}
```
