### ISSUE TITLE
BUG: x-axis labels of xyaxes diagram are incorrectly positioned on iOS

### ISSUE THREAD

**Issue by kristofk01** [ray-pH/diagramatics#7]
When viewing a plot which contains `xyaxes` on mobile the x-axis labels are positioned too far from the x-axis.

See below:
![image](https://github.com/ray-pH/diagramatics/assets/23499974/8fd85491-e171-489e-b8eb-fe14f9ca14b8)

Tested on
iOS 17.x Safari

The bug does not occur on desktop browsers - even when viewed at the same screen width.

**Comment by ray-pH** [comment]
I don't have easy access to an iOS device, but I'll try to figure out how to handle this bug

**Comment by ray-pH** [comment]
I'm curious, could you show me what this [example diagram ](https://photon-ray.xyz/diagramatics-site/examples/)looks like in iOS?
![image](https://github.com/ray-pH/diagramatics/assets/57003984/c2288303-bcc0-4d42-aba7-b39bf2513fed)

**Comment by kristofk01** [comment]
This is what it looks like on Safari iOS, and the same issue occurs on Chrome for iPhone.
![image](https://github.com/ray-pH/diagramatics/assets/23499974/8fe52f47-15a5-4c19-aaf1-17ce957301e3)

**Comment by ray-pH** [comment]
fixed in diagramatics@1.2.4
