### ISSUE TITLE
Click interactions on Diagrams: adding id

### ISSUE THREAD

**Issue by visualbuffer** [ray-pH/diagramatics#9]
[feature request]
**Description**
I wanted click / hover interactions in my diagrams. We could extend the Interactivity class. But a simpler approach might be to include an id attribuite in the diagram class and have the same in the respective svgelements. If I understand correctly we need to modify the [`diagram_combine()`](https://github.com/ray-pH/diagramatics/blob/95fcc2803cd5d10c00c88890eb4fcb5ffed1d033/src/diagram.ts#L909) and the functions within `f_draw_to_svg()`: [`draw_polygon()`](https://github.com/ray-pH/diagramatics/blob/95fcc2803cd5d10c00c88890eb4fcb5ffed1d033/src/draw_svg.ts#L58) etc

**Comment by ray-pH** [comment]
I'm currently working on something like that in the `dragdrop` branch (I'm trying to implement a drag and drop interaction).

**Comment by ray-pH** [comment]
The implementation is done, I'll write the guide/example for it in a bit

**Comment by ray-pH** [comment]
The guide is now online. For click interaction, you can use
[Interactive.button_click](https://photon-ray.xyz/diagramatics-site/guides/interactivity/#Interactive.button_click)

Or if you need more control, there's also [Interactive.custom_object](https://photon-ray.xyz/diagramatics-site/guides/interactivity#Interactive.custom_object).

**Comment by visualbuffer** [comment]
Super, will go through it
